# Permalinks
permalink:           pretty

# Setup
title:               HF
tagline:             
url:                 "https://www.happyfrog.life"
paginate:            
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              
  url:               
  email:             

# Custom vars
version:             
github:
  repo:              

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-autoprefixer

autoprefixer:
  browsers:
    - last 2 versions

exclude:
  - node_modules
